 - hosts: localhost
   become: true
   vars:
     myusername: tsimonq2
     myhome: /home/tsimonq2
     hostname: semantic
   tasks:
     # Add the Element repositories
     - include: tasks/repos.yml
     # Bootstrap the packages needed on the system
     - include: tasks/packages.yml
