- name: Install development packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      # https://wiki.ubuntu.com/SimpleSbuild
      - sbuild
      - debhelper
      - ubuntu-dev-tools
      - piuparts
      - apt-cacher-ng
      - moreutils
      # General tools
      - build-essential
      - pkg-kde-tools
      - check-all-the-things
      - autopkgtest
      - git
      - bzr
      - python3-launchpadlib
      - software-properties-common
      - arcanist

- name: Install a desktop environment
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - lubuntu-desktop

- name: Install standard working tools
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - ubuntu-standard 
      - firefox
      - thunderbird
      - telegram-desktop
      - vim
      - featherpad
      - kcalc
      - libreoffice
      - vlc
      - htop
      - pavucontrol-qt
      - partitionmanager
      - kdeconnect
      - neofetch
      - ssh
      - tmux
      - virt-manager
      - zsync
      - pastebinit
      - hplip
      - cups
      - cups-bsd
      - cups-client
      - snapd
      - apt-file
      - kde-spectacle
      - inkscape
      - kate
      - element-nightly

- name: Remove packages
  command: "apt -y purge {{ item }}"
  with_items:
    - postfix

- name: Install snaps
  command: "snap install {{ item }}"
  with_items:
    - lxd
    - 
